//knowledge areas
export const LIST_KNOWLEDGEAREAS = 'LIST_KNOWLEDGEAREAS'
export const LIST_SPECIALITIES = 'LIST_SPECIALITIES'

//knowledge areas tutor (specialities)
export const ADD_SPECIALITY_TUTOR = 'ADD_SPECIALITY_TUTOR'
export const DELETE_SPECIALITY_TUTOR = 'DELETE_SPECIALITY_TUTOR'
export const LIST_SPECIALITIES_TUTOR = 'LIST_SPECIALITIES_TUTOR'
export const SET_SPECIALITY_TUTOR = 'SET_SPECIALITY_TUTOR'

export const SET_IS_CREATE = 'SET_IS_CREATE'
