/*Register TUTOR*/

export const ADD_TUTOR = 'ADD_TUTOR'
export const LIST_TUTOR = 'LIST_TUTOR'
export const ADD_TUTOR_GOOGLE = 'ADD_TUTOR_GOOGLE'

/*Register STUDENT*/

export const ADD_STUDENT = 'ADD_STUDENT'
export const UPDATE_STUDENT = 'UPDATE_STUDENT'
export const DELETE_STUDENT = 'DELETE_STUDENT'
export const GET_STUDENT = 'GET_STUDENT'
export const LIST_STUDENT = 'LIST_STUDENT'
export const ADD_STUDENT_GOOGLE = 'ADD_STUDENT_GOOGLE'

/*Login*/

export const USER_LOADED = 'USER_LOADED'
export const USER_LOADING = 'USER_LOADING'
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS'
export const AUTH_ERROR = 'AUTH_ERROR'
export const LOGIN_FAIL = 'LOGIN_FAIL'
export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS'

//Other
export const UPDATE_INFORMATION = 'UPDATE_INFORMATION'
export const ACTION_RUNNING = 'ACTION_RUNNING'
export const ACTION_END = 'ACTION_END'
export const FINISHED_LOADING = 'FINISHED_LOADING'
