export const LIST_SPECIALITIES_TUTOR = 'LIST_SPECIALITIES_TUTOR'

export const ADD_SERVICE_TUTOR = 'ADD_SERVICE_TUTOR'
export const UPDATE_SERVICE_TUTOR = 'UPDATE_SERVICE_TUTOR'
export const DELETE_SERVICE_TUTOR = 'DELETE_SERVICE_TUTOR'
export const LIST_SERVICES_TUTOR = 'LIST_SERVICES_TUTOR'
export const SET_SERVICE_TUTOR = 'SET_SERVICE_TUTOR'

export const SET_IS_CREATE = 'SET_IS_CREATE'
